### PR TITLE
allow to disable the picker

### PR DESCRIPTION
**Pull request by janeisklar**
This commit allows to disable the timepicker when editing the input should not be allowed.

```html
<fm-timepicker fm-disabled="myModelFromMyControllerScope.disabled"></fm-timepicker>
```

### CODE REVIEW

**Comment by oliversalzburg** [comment]
Thanks for the PR, however, I have a couple issues with this one:
1. While the `&` binding is probably functionally equivalent in this case, as we don't really make use of two-way binding, I prefer the keep the bindings consistent and re-evaluate all of them at a later time.
2. I am very much in favor of prefixing the attributes used in the directive with `fm`. It was a poor choice not to prefix them all right from the start. However, again, I prefer to keep the style consistent for the time being and change all attributes to a prefixed version later.
3. The change does not take the sequential mode into account.

I added the feature to disable the time picker in the latest revision though. I'd be happy to read your comments.

**Comment by janeisklar** [comment]
1. I'm not sure why I chose '&', I suppose it doesn't matter.
2. We are using gulp-angular-htmlify, which automatically adds the 'data-' prefix for a list of custom attribute prefixes (such as 'fm-'). Naming it fm-disabled was therefore simply more convenient for me, but of course I agree that it makes more sense to name all attributes in the same way. Having said that, I'm not sure whether the attribute name 'disabled' is such a great idea, as it is a standard HTML attribute and could theoretically impact the way browsers deal with the element. Furthermore, some unspecific CSS styles may be affecting its appearance. Then again, the 'disabled' attribute should theoretically be limited to input fields only and you are planning to prefix everything anyway, so I guess it's fine.
3. Didn't know about that, thanks!

Thank you for sorting out those issues and getting it merged so quickly!

**Comment by oliversalzburg** [comment]
I totally agree regarding the `disabled` attribute. I'm already working on pushing out a commit that prefixes all attributes. This will obviously a major release due to it being a breaking change, but you can monitor the dev branch to see where I'm going. Feedback is welcome :)

**Comment by oliversalzburg** [comment]
Prefixed attributes are now live in 4.0.0

**Comment by janeisklar** [comment]
That's great, thanks for getting these prefixes integrated so fast! I can't test it right now, but from looking at the code I think you might have re-introduced issue https://github.com/fairmanager/fm-timepicker/pull/8, as you are using scope.reference.tz() whenever moment.tz is defined. We are using moment.tz, but we are not using a reference time (our use case is that the specified time should always be in the server timezone and should be taken as is and not be converted which we are taking care of on our own). I think we might run into trouble again when not setting a reference time, but I may have missed something though as you did quite a bit of refactoring :)

**Comment by oliversalzburg** [comment]
@janeisklar The fix from #8 should still be in there: https://github.com/fairmanager/fm-timepicker/blob/dev/src/fm-timepicker.js#L528

**Comment by janeisklar** [comment]
I just wanted to let you know that I have just integrated your changes and it is working fine. Thank you!

**Comment by oliversalzburg** [comment]
@janeisklar Awesome. Thanks for the feedback and your contributions :)

**Pull request closed without merging**
